### ISSUE TITLE
프로젝트 선정

### ISSUE THREAD

**Issue by haracejacob** [17-1-SKKU-OSS/011A#1]
현재 저희가 커뮤니티에 기여할 프로젝트로 Caffe2를 선정하였습니다.

Github : https://github.com/caffe2/caffe2
Homeplage : https://caffe2.ai

입니다.

그리고 기여방안으로
- 오탈자 수정
- 한글 번역
-  Example 만들기
- 버그 수정
- 성능 개선

등이 있지만 위의 3개 위주로 하려고 계획중입니다.

**Comment by ASTONISHER** [comment]
오픈소스에 기여하는 방법으로 참고할 수 있는 블로그
> http://www.bloter.net/archives/197960

코드 오탈자 잡아주는 Linter소개 블로그
> https://subicura.com/2016/07/11/coding-convention.html

스펠링 체크해주는 프로젝트
> https://github.com/myint/scspell
> https://github.com/ssut/py-hanspell
