### ISSUE TITLE
번역 검수 요청

### ISSUE THREAD

**Issue by ASTONISHER** [17-1-SKKU-OSS/011A#11]
Wiki에 등록된 번역과 홈페이지의 원문을 보시고 2차 검수를 해 주셨으면 합니다. 

전체가 어렵다면 `한글(영어)`이렇게 표시 해 둔 부분이나 영어로 남아있는 부분을 중점적으로 봐주세요!

ex] Toy Regression

ex]  이미지 전처리(Image Pre-Processing)

**Comment by haracejacob** [comment]
영어를 잘 하진 않지만 번역이 어색한 부분을 체크해서 이메일로 문서 보넀습니다!

**Comment by ASTONISHER** [comment]
4개 post에 대하여 번역 검수 완료.
