### ISSUE TITLE
Caffe2 기여 계획

### ISSUE THREAD

**Issue by haracejacob** [17-1-SKKU-OSS/011A#2]
각자 기여할 방법에  대해 써주세요

저는 소스코드의 오탈자를 찾아서 수정할 계획입니다.

Python 라이브러리 Grammar-check  https://pypi.python.org/pypi/grammar-check/1.3.1
Python 라이브러리 Language-check https://github.com/myint/language-check

위의 라이브러리로 파이썬에서 자동으로 모든 텍스트파일의 오탈자를 체크하는 프로그램을 만들 예정입니다.

**Comment by ASTONISHER** [comment]
저는 소스코드 내에 있는 주석 오탈자를 찾아서 수정 해보겠습니다. 
> https://github.com/myint/scspell
>https://github.com/ssut/py-hanspell

여건이 된다면 docs의 한글화도 할 계획입니다.
> https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile

**Comment by HWhale** [comment]
Caffe2 사용 방법을 익힌 뒤, 간단한 tutorial용 코드를 만들어 commit하고자 합니다.

Caffe2 tutorial overview : https://caffe2.ai/docs/tutorials.html

**Comment by HWhale** [comment]
Caffe2 쪽에서 Tutorial 추가를 긍정적으로 생각하고 있는 것 같습니다.
기회가 된다면 다른 분들도 참여하시면 좋을 듯 합니다.

>Some tutorials have been generously provided by the Caffe community and we welcome more contributions of this kind to help others get ramped up more quickly and to try out the many different uses of Caffe2.
