### ISSUE TITLE
static page 관리

### ISSUE THREAD

**Issue by ASTONISHER** [17-1-SKKU-OSS/011A#3]
저희 static page도 관리 해야할 것 같습니다.
우선 제가 테마 받아서 기본적인 것들 해 놓겠습니다 :)

**Comment by ASTONISHER** [comment]
![image](https://cloud.githubusercontent.com/assets/18477439/26300892/67926b80-3f1a-11e7-87e4-66b0b6b997db.png)

실패의 흔적.. 테마 어떻게 적용해야해요..?ㅜㅜ
찾아봤을때 이게 젤 마음에 들었는데 조금 이따가 다시 해봐야겠어요.

>  https://taylantatli.github.io/Moon/moon-theme/

**Comment by ASTONISHER** [comment]
095A팀의 static page를 참고할 것.

**Comment by HWhale** [comment]
새로운 repository를 생성하지 않고 가져오는 법으로 찾고 있나요?
저도 관련해서 시도해 보고 있는데, 테마 사이트에 게시되어 있는 방법은 fork를 이용한 방법이라
현재 repository를 보존한 채로 저 테마를 적용하려면 어떻게 해야 할 지 잘 모르겠네요

**Comment by ASTONISHER** [comment]
네, 새로운 repository를 생성하지 않고 가져오고 싶었어요!
제가 생각 해본건, 전체를 클론해서 폴더 하나를 만들어 넣어보는 건데, 이렇게 하면 너무 복잡해지려나요?
