### ISSUE TITLE
Static web page적용

### ISSUE THREAD

**Issue by ASTONISHER** [17-1-SKKU-OSS/011A#6]
page폴더를 갖고와서 넣어버렸습니다. 이렇게 해도 되는지는 잘 모르겠지만, 페이지는 제대로 생성이 됐습니다. 기본 언어를 영어로 작성하려고 합니다. caffe2측에 pull request를 보낼 때 주소도 함께 보내서 뭐랄까, 우리 프로젝트의 중요성(?)을 어필하고 싶어서... 헤헿

1. 혹시 이런 방법이 아니라 다른 방법으로 page를 만들어야한다면 알려주세요. 
2. _post파일에 가면 post를 올릴 수 있습니다. 진척상황이 있을 때마다 Post를 올려주세요. 영어로 하면 좋겠지만, 별로인것 같으면 한글도 좋습니다.
3. 페이지 들어가시면, project란이 있는데 각자 맡은 project를 간단하게 설명하는 페이지를 만들어도 좋을 것 같습니다. 

열심히 해봐요!!

**Comment by ASTONISHER** [comment]
아, 페이지를 만들고나서 이곳에 알려주시면 좋을 것 같습니다.

- config_yml(메인) 완료
- about 폴더(소개 페이지) 완료

 post와 project폴더에는 dummy data가 들어있습니다. 삭제하고 진행 해 주시면 됩니다. tags는 따로 손 댈 필요는 없어보이지만 고쳐야 할 부분이 있다면 고쳐주세요! 다른 페이지들도 수정이 필요할 것 같다면 고쳐주세요!

**Comment by ASTONISHER** [comment]
파일들을 하나의 폴더로 넣어보려고 했는데, 어떻게 해야할지 몰라 이슈 남깁니다!

일단 다 클론해서 한 폴더에 넣었는데 그걸 drag&drop방식으로 커밋하려고하니 
한번에 100개의 파일만 업로드 가능하다고 하더라구요.

bash로 커밋을 해보려고하는데, 수업시간에 **도와주셨으면** 합니다..
제가 cmd로 git을 쓰는데 익숙하지 않아서 다 날려버릴까봐 무서워서요!

**Comment by haracejacob** [comment]
정적웹페이지를 추가하면서 root directory 부분에 폴더가 많이 늘어났는데 혹시 이걸 한 폴더에 넣어서 깔끔하게 보일 수 있을까요?
아마도 _config.yml 파일 14번째 줄의 permalink를 수정하면 될 듯 싶습니다.
https://jekyllrb.com/docs/permalinks/ 이걸 참조하셔도 좋을듯해요~

**Comment by ASTONISHER** [comment]
static_page 폴더를 만들어서 넣었습니다!
commit 삭제하는 것(=폴더를 없애는 것)에 어려움을 겪어서 그 해결 방안을 찾아봤어요.
> git rm -r --cached "지울 폴더명"
> git commit -m "commit message"
> git push origin master

이렇게 하면 해결 되더라구요!

**Comment by ASTONISHER** [comment]
파일 directory를 옮겼더니 페이지가 사라졌어요 ㅠㅠ
제가 다시 만들어두겠습니다.....

**Comment by ASTONISHER** [comment]
![image](https://cloud.githubusercontent.com/assets/18477439/26589917/36dc494a-4594-11e7-904f-bde88dc6849b.png)
14번 시도했으나 어떻게 페이지를 다시 보이게 하는지 모르겠습니다.

config.yml파일에서 시도 해본 목록입니다.
1. permerlink:  /static_page/:title  << static_page경로 추가해보기
2. permerlink:  /:static_page/:title  <</: 라는 형식 따라서 추가해보기
3. 참조를 위해 올려주신 지킬 안내사이트를 뒤적이다보니 파일의 종류별 위치가 디폴트 값으로 '.'이 설정되어있더라구요. 그래서 이 source를 추가 해봤습니다.
source:  .static_page/

**Comment by ASTONISHER** [comment]
무슨짓을 해봐도 잘 안돼서 다 꺼내버리겠습니다ㅠㅠ
Google에 찾아봐도 '예쁜 테마를 적용시켜볼까요↗↗' 이런거만 나와서 슬퍼요ㅜㅜ

추후에라도 방법을 찾으시면 ISSUE남겨주세요! 이 ISSUE는 닫겠습니다!
